-- 新增菜品及套餐，所有语句可重复执行。

INSERT INTO dishes (type_id, name, detail, cover_url, status, create_time) SELECT 1, '青椒肉丝', '鲜嫩肉丝搭配爽脆青椒，咸香下饭。', 'http://localhost:8081/uploads/青椒肉丝.jpg', 1, NOW() WHERE NOT EXISTS (SELECT 1 FROM dishes WHERE name = '青椒肉丝');
INSERT INTO dishes (type_id, name, detail, cover_url, status, create_time) SELECT 1, '回锅肉', '五花肉肥而不腻，搭配蒜苗香气浓郁。', 'http://localhost:8081/uploads/回锅肉.jpg', 1, NOW() WHERE NOT EXISTS (SELECT 1 FROM dishes WHERE name = '回锅肉');
INSERT INTO dishes (type_id, name, detail, cover_url, status, create_time) SELECT 1, '水煮肉片', '麻辣鲜香的川味肉片，配菜丰富。', 'http://localhost:8081/uploads/水煮肉片.jpg', 1, NOW() WHERE NOT EXISTS (SELECT 1 FROM dishes WHERE name = '水煮肉片');
INSERT INTO dishes (type_id, name, detail, cover_url, status, create_time) SELECT 1, '清炒时蔬', '应季时蔬清爽脆嫩，健康解腻。', 'http://localhost:8081/uploads/清炒时蔬.jpg', 1, NOW() WHERE NOT EXISTS (SELECT 1 FROM dishes WHERE name = '清炒时蔬');
INSERT INTO dishes (type_id, name, detail, cover_url, status, create_time) SELECT 2, '凉拌木耳', '木耳爽脆，酸辣开胃。', 'http://localhost:8081/uploads/凉拌木耳.jpg', 1, NOW() WHERE NOT EXISTS (SELECT 1 FROM dishes WHERE name = '凉拌木耳');
INSERT INTO dishes (type_id, name, detail, cover_url, status, create_time) SELECT 2, '口水鸡', '鸡肉细嫩，麻辣鲜香，回味十足。', 'http://localhost:8081/uploads/口水鸡.jpg', 1, NOW() WHERE NOT EXISTS (SELECT 1 FROM dishes WHERE name = '口水鸡');
INSERT INTO dishes (type_id, name, detail, cover_url, status, create_time) SELECT 3, '玉米排骨汤', '玉米清甜，排骨软烂，汤味鲜美。', 'http://localhost:8081/uploads/玉米排骨汤.jpg', 1, NOW() WHERE NOT EXISTS (SELECT 1 FROM dishes WHERE name = '玉米排骨汤');
INSERT INTO dishes (type_id, name, detail, cover_url, status, create_time) SELECT 3, '西湖牛肉羹', '牛肉鲜香顺滑，口感细腻暖胃。', 'http://localhost:8081/uploads/西湖牛肉羹.jpg', 1, NOW() WHERE NOT EXISTS (SELECT 1 FROM dishes WHERE name = '西湖牛肉羹');
INSERT INTO dishes (type_id, name, detail, cover_url, status, create_time) SELECT 4, '扬州炒饭', '米粒分明，配料丰富，香气十足。', 'http://localhost:8081/uploads/扬州炒饭.jpg', 1, NOW() WHERE NOT EXISTS (SELECT 1 FROM dishes WHERE name = '扬州炒饭');
INSERT INTO dishes (type_id, name, detail, cover_url, status, create_time) SELECT 4, '牛肉面', '劲道面条搭配浓郁牛肉汤，暖心暖胃。', 'http://localhost:8081/uploads/牛肉面.jpg', 1, NOW() WHERE NOT EXISTS (SELECT 1 FROM dishes WHERE name = '牛肉面');
INSERT INTO dishes (type_id, name, detail, cover_url, status, create_time) SELECT 5, '拿铁咖啡', '醇香咖啡与绵密奶泡的经典搭配。', 'http://localhost:8081/uploads/拿铁咖啡.jpg', 1, NOW() WHERE NOT EXISTS (SELECT 1 FROM dishes WHERE name = '拿铁咖啡');
INSERT INTO dishes (type_id, name, detail, cover_url, status, create_time) SELECT 5, '蜂蜜柚子茶', '清甜柚香搭配蜂蜜，清爽解腻。', 'http://localhost:8081/uploads/蜂蜜柚子茶.jpg', 1, NOW() WHERE NOT EXISTS (SELECT 1 FROM dishes WHERE name = '蜂蜜柚子茶');

INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '小份', '300g', 26.00, NOW() FROM dishes d WHERE d.name = '青椒肉丝' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '小份' AND dp.specs = '300g');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '中份', '500g', 36.00, NOW() FROM dishes d WHERE d.name = '青椒肉丝' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '中份' AND dp.specs = '500g');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '大份', '800g', 52.00, NOW() FROM dishes d WHERE d.name = '青椒肉丝' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '大份' AND dp.specs = '800g');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '小份', '300g', 28.00, NOW() FROM dishes d WHERE d.name = '回锅肉' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '小份' AND dp.specs = '300g');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '中份', '500g', 40.00, NOW() FROM dishes d WHERE d.name = '回锅肉' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '中份' AND dp.specs = '500g');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '大份', '800g', 56.00, NOW() FROM dishes d WHERE d.name = '回锅肉' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '大份' AND dp.specs = '800g');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '小份', '300g', 36.00, NOW() FROM dishes d WHERE d.name = '水煮肉片' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '小份' AND dp.specs = '300g');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '中份', '500g', 52.00, NOW() FROM dishes d WHERE d.name = '水煮肉片' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '中份' AND dp.specs = '500g');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '大份', '800g', 72.00, NOW() FROM dishes d WHERE d.name = '水煮肉片' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '大份' AND dp.specs = '800g');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '标准份', '350g', 18.00, NOW() FROM dishes d WHERE d.name = '清炒时蔬' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '标准份' AND dp.specs = '350g');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '标准份', '250g', 14.00, NOW() FROM dishes d WHERE d.name = '凉拌木耳' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '标准份' AND dp.specs = '250g');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '标准份', '350g', 26.00, NOW() FROM dishes d WHERE d.name = '口水鸡' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '标准份' AND dp.specs = '350g');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '小碗', '300ml', 12.00, NOW() FROM dishes d WHERE d.name = '玉米排骨汤' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '小碗' AND dp.specs = '300ml');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '大碗', '500ml', 20.00, NOW() FROM dishes d WHERE d.name = '玉米排骨汤' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '大碗' AND dp.specs = '500ml');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '小碗', '300ml', 14.00, NOW() FROM dishes d WHERE d.name = '西湖牛肉羹' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '小碗' AND dp.specs = '300ml');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '大碗', '500ml', 22.00, NOW() FROM dishes d WHERE d.name = '西湖牛肉羹' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '大碗' AND dp.specs = '500ml');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '标准份', '400g', 18.00, NOW() FROM dishes d WHERE d.name = '扬州炒饭' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '标准份' AND dp.specs = '400g');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '标准份', '500g', 22.00, NOW() FROM dishes d WHERE d.name = '牛肉面' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '标准份' AND dp.specs = '500g');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '杯', '350ml', 16.00, NOW() FROM dishes d WHERE d.name = '拿铁咖啡' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '杯' AND dp.specs = '350ml');
INSERT INTO dishes_package (dishes_id, name, specs, price, create_time) SELECT d.id, '杯', '500ml', 12.00, NOW() FROM dishes d WHERE d.name = '蜂蜜柚子茶' AND NOT EXISTS (SELECT 1 FROM dishes_package dp WHERE dp.dishes_id = d.id AND dp.name = '杯' AND dp.specs = '500ml');
